name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: PHP API client
        # Get the official PHP client library for Google APIs 
        #   We are hard coding v2.18.2 for PHP 8.0 - PHP 8.2
        #   Lets see if this breaks! :-p 
        #   https://github.com/googleapis/google-api-php-client/releases
        run: |
          mkdir -p google-api-php-client
          wget https://github.com/googleapis/google-api-php-client/releases/download/v2.18.2/google-api-php-client--PHP8.0.zip -O google-api-php-client/google-api-php-client.zip
          unzip google-api-php-client/google-api-php-client.zip -d google-api-php-client
      - name: Port Knock
        # We have to add the "|| true" else the nc times out (as we want) but 
        #   returns an error code which stops GitHub Actions from continuining
        run: nc -w 1 ${{ secrets.REMOTE_HOST }} ${{ secrets.PORT_KNOCK_PORT }} || true
      - name: Adding Known Hosts
        # We tried Using SSHFP instead of doing this but GitHub's resolvers aren't secure 
        #   which is a requirement. The below is not "secure" however we are using a strong
        #   SSH Key to an isolated env so am happy that this is OK for what we are doing.
        run: ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        # Run with --delete to tidy up old files but add filters so we don't delete 
        #   config files that are already setup on the server
        run: rsync -rptv --delete --exclude=.git --filter='P /config/*.config' ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:displayboard/
